### ISSUE TITLE
[bug](snap): Casting global ethereum object to any obfuscates `resolveDid` error

### ISSUE THREAD

**Issue by radleylewis** [blockchain-lab-um/masca#547] opened 2024-01-17 08:42 UTC
### Describe the bug

**Overview**
Within the `networks` each `new Web3Provider` has its first argument as the global ethereum object. However, this obfuscates a bug that occurs when attempting to resolve a did that has been amended. 

```typescript
// networks code from the veramo agent
const networks = [
      {
        name: 'mainnet',
        provider: new Web3Provider(ethereum as any),
      },
      {
        name: '0x05',
        provider: new Web3Provider(ethereum as any),
      },
      {
        name: 'goerli',
        provider: new Web3Provider(ethereum as any),
        chainId: '0x5',
      },
      {
        name: 'sepolia',
        provider: new Web3Provider(ethereum as any),
        chainId: '0xaa36a7',
        registry: '0x03d5003bf0e79c5f5223588f347eba39afbc3818',
      },
    ]
```

For example, when resolving a did which has been amended (e.g. has had a `serviceEndpoint` added to the didDoc), it will not resolve, but will instead throw an error of `provider.getLogs()` is not defined/no such function.

Below is a screenshot of the specific line of code (see: `ethr-did-resolver/src/resolver.ts`):

![image](https://github.com/blockchain-lab-um/masca/assets/40852773/ca3aae3e-2502-4326-a0d0-6a02dc2855d6)

### To Reproduce

1. create a did/generate a new did 
2. update the did for a change/amendment (e.g. add a `serviceEndpoint` to the didDoc
3. attempt to resolve the changed/amended did with `resolveDID` which will fail as outlined above.

### Expected behavior

The `resolveDID` rpc call should return the didDoc associated with the did, along with any amendments.

**Comment by martines3000** [comment] 2024-01-17 10:33
Hi. Thanks for the detailed description.

Could you provide me with 1 did that was amended, so I can use it to debug the code ?

Thank you.

**Comment by radleylewis** [comment] 2024-01-18 01:31
Sure thing! The following did won't resolve with masca's `resolveDid` rpc call:
```bash
did:ethr:sepolia:0x0371ab768c9d855e3b5c2bd94ba425d9105e122c1b424467f79df53e3175b30b3d
```
The resolved didDoc should look like the below (I am able to resolve it from a nodejs Veramo configuration using `ethr-did-resolver`):

```json
{
  id: 'did:ethr:sepolia:0x0371ab768c9d855e3b5c2bd94ba425d9105e122c1b424467f79df53e3175b30b3d',
  verificationMethod: [
    {
      id: 'did:ethr:sepolia:0x0371ab768c9d855e3b5c2bd94ba425d9105e122c1b424467f79df53e3175b30b3d#controller',
      type: 'EcdsaSecp256k1RecoveryMethod2020',
      controller: 'did:ethr:sepolia:0x0371ab768c9d855e3b5c2bd94ba425d9105e122c1b424467f79df53e3175b30b3d',
      blockchainAccountId: 'eip155:11155111:0xf6CE77B0D921940726cC8742c03914C9312a79b3'
    },
    {
      id: 'did:ethr:sepolia:0x0371ab768c9d855e3b5c2bd94ba425d9105e122c1b424467f79df53e3175b30b3d#controllerKey',
      type: 'EcdsaSecp256k1VerificationKey2019',
      controller: 'did:ethr:sepolia:0x0371ab768c9d855e3b5c2bd94ba425d9105e122c1b424467f79df53e3175b30b3d',
      publicKeyHex: '0371ab768c9d855e3b5c2bd94ba425d9105e122c1b424467f79df53e3175b30b3d'
    }
  ],
  authentication: [
    'did:ethr:sepolia:0x0371ab768c9d855e3b5c2bd94ba425d9105e122c1b424467f79df53e3175b30b3d#controller',
    'did:ethr:sepolia:0x0371ab768c9d855e3b5c2bd94ba425d9105e122c1b424467f79df53e3175b30b3d#controllerKey'
  ],
  assertionMethod: [
    'did:ethr:sepolia:0x0371ab768c9d855e3b5c2bd94ba425d9105e122c1b424467f79df53e3175b30b3d#controller',
    'did:ethr:sepolia:0x0371ab768c9d855e3b5c2bd94ba425d9105e122c1b424467f79df53e3175b30b3d#controllerKey'
  ],
  service: [
    {
      id: 'did:ethr:sepolia:0x0371ab768c9d855e3b5c2bd94ba425d9105e122c1b424467f79df53e3175b30b3d#service-3',
      type: 'DIDCommMessaging',
      serviceEndpoint: 'https://ddc1.serveo.net/api/ssdt/messaging'
    }
  ],
  '@context': [
    'https://www.w3.org/ns/did/v1',
    'https://w3id.org/security/suites/secp256k1recovery-2020/v2',
    'https://w3id.org/security/v3-unstable'
  ]
}
```

**Comment by hylim-tech-lover** [comment] 2024-01-18 02:25
@martines3000 I faced the similar issue and in addition to the information that @radleylewis have provided, I have constructed a simply **conditional flowchart** to illustrate on the behavior of `DID resolver configuration` that I have observed along the troubleshooting process. 

![image](https://github.com/blockchain-lab-um/masca/assets/81916319/f4c4b403-7e0b-42ad-97e7-a31df248121d)


Hope it could give more insights and fast-tracked the root cause analysis process

**Comment by martines3000** [comment] 2024-01-18 11:08
Hey @hylim-tech-lover @radleylewis.

I created a new release (v1.2.0-beta.2) available here:
https://www.npmjs.com/package/@blockchain-lab-um/masca/v/1.2.0-beta.2

You will need MetaMask Flask for this version. You can test it on our [beta dapp](https://beta.masca.io/).

The issues should be resolve, if this is not the case, please let me know. Thank you.

**Comment by hylim-tech-lover** [comment] 2024-01-19 02:34
Hi @martines3000 thanks for heads-up! Unfortunately I couldn't find any place to test the `resolveDid` function from [beta dapp](https://beta.masca.io/) that you mentioned.

However, I did use Masca SDK in my DAPP and managed to `resolve the did successfully` now! It is safe to say it does work. Cheers! 😄 

Code snippet of Masca SDK

```ts
      console.log(`Connecting to MASCA SNAP app`);
      const enableResult = await enableMasca(selectedAccount, {
        snapId: 'npm:@blockchain-lab-um/masca',
        version: '1.2.0-beta.2',
      });

      const mascaSnap = enableResult.data.getMascaApi();

      await mascaSnap.setCurrentAccount({
        account: ...,
      });

     const resolveDid = await mascaSnap.resolveDID(...);

     console.log(
       'did resolved result: ',
       resolveDid.data,
     );
...
```

**Comment by martines3000** [comment] 2024-01-19 09:43
Thank you for helping test Masca and reporting the issue.

I will close this issue now. If you find anything else not working correctly, please notify us 🚀 .

**Closed by martines3000** 2024-01-19 09:43 UTC
Labels: bug

**Comment by radleylewis** [comment] 2024-01-19 12:31
Thanks @martines3000 . That's awesome - very much appreciated!
